# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  
  desc "Submit a new release build to Google Play's Production track"
  lane :release do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter pub upgrade"
    sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons"

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Upload to internal testing track"
  lane :test do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter pub upgrade"
    sh "cat pubspec.lock"
    sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons --dart-define='deployment-mode=test'"

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end