# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new release build to Google Play's Production track"
  lane :release do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter pub upgrade"
    sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons"

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Promote internal track to closed"
  lane :promote_internal_to_closed do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter pub upgrade"

    sh "pwd"
    # pubspec_content = YAML.load_file('../pubspec.yaml')
    # # current_version_code = google_play_track_version_codes(track: 'internal')
    # version_string = pubspec_content['version']
    # version_parts = version_string.split('+')
    # if version_parts.size == 2
    #   version_number = version_parts[1].to_i
    #   new_version_number = version_number + 1
    #   pubspec_content['version'] = "#{version_parts[0]}+#{new_version_number}"
    # else
    #   UI.user_error!("Version string format is incorrect")
    # end
    # File.open(pubspec_path, 'w') { |f| f.write(pubspec_content.to_yaml) }

    # sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons"
    # upload_to_play_store(
    #   track: 'internal',
    #   track_promote_to: 'closed',
    #   aab: '../build/app/outputs/bundle/release/app-release.aab',
    # )
  end
end