name: Upload to Google Store
run-name: ${{github.actor}} is pushing to branch and deploying to Google Store

on:
    push:
        branches:
        - panosfunk/google_store
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: fastlane beta